# Generated by Django 2.1.4 on 2019-01-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
